/**
 * Sanitised captures from `fgj` v0.4.0 against a real Forgejo instance, so the decoders are
 * proved against the raw Gitea `PullRequest` struct rather than against a hand-written shape.
 * Hostnames, logins, emails, avatar hashes, titles and bodies are replaced; the field set,
 * nesting and null-vs-absent choices are `fgj`'s own.
 *
 * The three entries cover the states that matter: open, merged (Forgejo files it under
 * `state: "closed"` and flags `merged: true`) and plain closed.
 */
export const FORGEJO_PR_LIST_JSON = `[
  {
    "id": 57,
    "url": "https://forgejo.example.test/octocat/widgets/pulls/37",
    "number": 37,
    "user": {
      "id": 12,
      "login": "octocat",
      "login_name": "",
      "source_id": 0,
      "full_name": "",
      "email": "octocat@example.test",
      "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
      "language": "en-US",
      "is_admin": false,
      "last_login": "2026-05-25T18:27:26+12:00",
      "created": "2026-05-25T18:25:12+12:00",
      "restricted": false,
      "active": true,
      "prohibit_login": false,
      "location": "",
      "website": "",
      "description": "",
      "visibility": "private",
      "followers_count": 0,
      "following_count": 0,
      "starred_repos_count": 0
    },
    "title": "Adopt the read_document helper",
    "body": "Sanitised capture.",
    "labels": [],
    "milestone": null,
    "assignee": null,
    "assignees": null,
    "state": "open",
    "draft": false,
    "is_locked": false,
    "comments": 6,
    "html_url": "https://forgejo.example.test/octocat/widgets/pulls/37",
    "diff_url": "https://forgejo.example.test/octocat/widgets/pulls/37.diff",
    "patch_url": "https://forgejo.example.test/octocat/widgets/pulls/37.patch",
    "mergeable": true,
    "merged": false,
    "merged_at": null,
    "merge_commit_sha": null,
    "merged_by": null,
    "allow_maintainer_edit": false,
    "base": {
      "label": "main",
      "ref": "main",
      "sha": "9966f9e6845b1e1165ac04789daefde50b06e54a",
      "repo_id": 11,
      "repo": {
        "id": 11,
        "owner": {
          "id": 5,
          "login": "octocat",
          "login_name": "",
          "source_id": 0,
          "full_name": "",
          "email": "octocat@example.test",
          "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
          "language": "",
          "is_admin": false,
          "last_login": "0001-01-01T00:00:00Z",
          "created": "2026-05-12T10:55:46+12:00",
          "restricted": false,
          "active": false,
          "prohibit_login": false,
          "location": "",
          "website": "",
          "description": "",
          "visibility": "private",
          "followers_count": 0,
          "following_count": 0,
          "starred_repos_count": 0
        },
        "name": "widgets",
        "full_name": "octocat/widgets",
        "description": "Octocat widgets - primary repo",
        "empty": false,
        "private": true,
        "fork": false,
        "template": false,
        "parent": null,
        "mirror": false,
        "size": 9507,
        "html_url": "https://forgejo.example.test/octocat/widgets",
        "ssh_url": "ssh://git@forgejo.example.test/octocat/widgets.git",
        "clone_url": "https://forgejo.example.test/octocat/widgets.git",
        "original_url": "",
        "website": "",
        "stars_count": 0,
        "forks_count": 0,
        "watchers_count": 2,
        "open_issues_count": 0,
        "open_pr_counter": 2,
        "release_counter": 0,
        "default_branch": "main",
        "archived": false,
        "created_at": "2026-06-24T11:33:56+12:00",
        "updated_at": "2026-09-10T00:42:47+12:00",
        "permissions": {
          "admin": false,
          "push": true,
          "pull": true
        },
        "has_issues": true,
        "internal_tracker": {
          "enable_time_tracker": true,
          "allow_only_contributors_to_track_time": true,
          "enable_issue_dependencies": true
        },
        "has_wiki": false,
        "has_pull_requests": true,
        "has_projects": false,
        "has_releases": true,
        "ignore_whitespace_conflicts": false,
        "allow_fast_forward_only_merge": true,
        "allow_merge_commits": true,
        "allow_rebase": true,
        "allow_rebase_explicit": true,
        "allow_squash_merge": true,
        "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
        "internal": false,
        "mirror_interval": "",
        "mirror_updated": "0001-01-01T00:00:00Z",
        "default_merge_style": "merge",
        "projects_mode": null,
        "default_delete_branch_after_merge": false,
        "object_format_name": "sha1"
      }
    },
    "head": {
      "label": "feat/read-document",
      "ref": "feat/read-document",
      "sha": "98375403536bb501dc015fd411c487c8b26ab0c0",
      "repo_id": 11,
      "repo": {
        "id": 11,
        "owner": {
          "id": 5,
          "login": "octocat",
          "login_name": "",
          "source_id": 0,
          "full_name": "",
          "email": "octocat@example.test",
          "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
          "language": "",
          "is_admin": false,
          "last_login": "0001-01-01T00:00:00Z",
          "created": "2026-05-12T10:55:46+12:00",
          "restricted": false,
          "active": false,
          "prohibit_login": false,
          "location": "",
          "website": "",
          "description": "",
          "visibility": "private",
          "followers_count": 0,
          "following_count": 0,
          "starred_repos_count": 0
        },
        "name": "widgets",
        "full_name": "octocat/widgets",
        "description": "Octocat widgets - primary repo",
        "empty": false,
        "private": true,
        "fork": false,
        "template": false,
        "parent": null,
        "mirror": false,
        "size": 9507,
        "html_url": "https://forgejo.example.test/octocat/widgets",
        "ssh_url": "ssh://git@forgejo.example.test/octocat/widgets.git",
        "clone_url": "https://forgejo.example.test/octocat/widgets.git",
        "original_url": "",
        "website": "",
        "stars_count": 0,
        "forks_count": 0,
        "watchers_count": 2,
        "open_issues_count": 0,
        "open_pr_counter": 2,
        "release_counter": 0,
        "default_branch": "main",
        "archived": false,
        "created_at": "2026-06-24T11:33:56+12:00",
        "updated_at": "2026-09-10T00:42:47+12:00",
        "permissions": {
          "admin": false,
          "push": true,
          "pull": true
        },
        "has_issues": true,
        "internal_tracker": {
          "enable_time_tracker": true,
          "allow_only_contributors_to_track_time": true,
          "enable_issue_dependencies": true
        },
        "has_wiki": false,
        "has_pull_requests": true,
        "has_projects": false,
        "has_releases": true,
        "ignore_whitespace_conflicts": false,
        "allow_fast_forward_only_merge": true,
        "allow_merge_commits": true,
        "allow_rebase": true,
        "allow_rebase_explicit": true,
        "allow_squash_merge": true,
        "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
        "internal": false,
        "mirror_interval": "",
        "mirror_updated": "0001-01-01T00:00:00Z",
        "default_merge_style": "merge",
        "projects_mode": null,
        "default_delete_branch_after_merge": false,
        "object_format_name": "sha1"
      }
    },
    "merge_base": "242b59e2c2f15ec1d35bf60289df53bffaf28e50",
    "due_date": null,
    "created_at": "2026-09-08T23:14:15+12:00",
    "updated_at": "2026-09-08T23:49:12+12:00",
    "closed_at": null
  },
  {
    "id": 61,
    "url": "https://forgejo.example.test/octocat/widgets/pulls/41",
    "number": 41,
    "user": {
      "id": 12,
      "login": "octocat",
      "login_name": "",
      "source_id": 0,
      "full_name": "",
      "email": "octocat@example.test",
      "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
      "language": "en-US",
      "is_admin": false,
      "last_login": "2026-05-25T18:27:26+12:00",
      "created": "2026-05-25T18:25:12+12:00",
      "restricted": false,
      "active": true,
      "prohibit_login": false,
      "location": "",
      "website": "",
      "description": "",
      "visibility": "private",
      "followers_count": 0,
      "following_count": 0,
      "starred_repos_count": 0
    },
    "title": "Rate ideas and assign rock owners",
    "body": "Sanitised capture.",
    "labels": [],
    "milestone": null,
    "assignee": null,
    "assignees": null,
    "state": "closed",
    "draft": false,
    "is_locked": false,
    "comments": 5,
    "html_url": "https://forgejo.example.test/octocat/widgets/pulls/41",
    "diff_url": "https://forgejo.example.test/octocat/widgets/pulls/41.diff",
    "patch_url": "https://forgejo.example.test/octocat/widgets/pulls/41.patch",
    "mergeable": true,
    "merged": true,
    "merged_at": "2026-09-10T00:42:45+12:00",
    "merge_commit_sha": "9966f9e6845b1e1165ac04789daefde50b06e54a",
    "merged_by": null,
    "allow_maintainer_edit": false,
    "base": {
      "label": "main",
      "ref": "main",
      "sha": "9966f9e6845b1e1165ac04789daefde50b06e54a",
      "repo_id": 11,
      "repo": {
        "id": 11,
        "owner": {
          "id": 5,
          "login": "octocat",
          "login_name": "",
          "source_id": 0,
          "full_name": "",
          "email": "octocat@example.test",
          "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
          "language": "",
          "is_admin": false,
          "last_login": "0001-01-01T00:00:00Z",
          "created": "2026-05-12T10:55:46+12:00",
          "restricted": false,
          "active": false,
          "prohibit_login": false,
          "location": "",
          "website": "",
          "description": "",
          "visibility": "private",
          "followers_count": 0,
          "following_count": 0,
          "starred_repos_count": 0
        },
        "name": "widgets",
        "full_name": "octocat/widgets",
        "description": "Octocat widgets - primary repo",
        "empty": false,
        "private": true,
        "fork": false,
        "template": false,
        "parent": null,
        "mirror": false,
        "size": 9507,
        "html_url": "https://forgejo.example.test/octocat/widgets",
        "ssh_url": "ssh://git@forgejo.example.test/octocat/widgets.git",
        "clone_url": "https://forgejo.example.test/octocat/widgets.git",
        "original_url": "",
        "website": "",
        "stars_count": 0,
        "forks_count": 0,
        "watchers_count": 2,
        "open_issues_count": 0,
        "open_pr_counter": 2,
        "release_counter": 0,
        "default_branch": "main",
        "archived": false,
        "created_at": "2026-06-24T11:33:56+12:00",
        "updated_at": "2026-09-10T00:42:47+12:00",
        "permissions": {
          "admin": false,
          "push": true,
          "pull": true
        },
        "has_issues": true,
        "internal_tracker": {
          "enable_time_tracker": true,
          "allow_only_contributors_to_track_time": true,
          "enable_issue_dependencies": true
        },
        "has_wiki": false,
        "has_pull_requests": true,
        "has_projects": false,
        "has_releases": true,
        "ignore_whitespace_conflicts": false,
        "allow_fast_forward_only_merge": true,
        "allow_merge_commits": true,
        "allow_rebase": true,
        "allow_rebase_explicit": true,
        "allow_squash_merge": true,
        "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
        "internal": false,
        "mirror_interval": "",
        "mirror_updated": "0001-01-01T00:00:00Z",
        "default_merge_style": "merge",
        "projects_mode": null,
        "default_delete_branch_after_merge": false,
        "object_format_name": "sha1"
      }
    },
    "head": {
      "label": "board/ma-3",
      "ref": "board/ma-3",
      "sha": "3e7c5bfa00e8ddbf217c6e8cb052252f3cc0a299",
      "repo_id": 11,
      "repo": {
        "id": 11,
        "owner": {
          "id": 5,
          "login": "octocat",
          "login_name": "",
          "source_id": 0,
          "full_name": "",
          "email": "octocat@example.test",
          "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
          "language": "",
          "is_admin": false,
          "last_login": "0001-01-01T00:00:00Z",
          "created": "2026-05-12T10:55:46+12:00",
          "restricted": false,
          "active": false,
          "prohibit_login": false,
          "location": "",
          "website": "",
          "description": "",
          "visibility": "private",
          "followers_count": 0,
          "following_count": 0,
          "starred_repos_count": 0
        },
        "name": "widgets",
        "full_name": "octocat/widgets",
        "description": "Octocat widgets - primary repo",
        "empty": false,
        "private": true,
        "fork": false,
        "template": false,
        "parent": null,
        "mirror": false,
        "size": 9507,
        "html_url": "https://forgejo.example.test/octocat/widgets",
        "ssh_url": "ssh://git@forgejo.example.test/octocat/widgets.git",
        "clone_url": "https://forgejo.example.test/octocat/widgets.git",
        "original_url": "",
        "website": "",
        "stars_count": 0,
        "forks_count": 0,
        "watchers_count": 2,
        "open_issues_count": 0,
        "open_pr_counter": 2,
        "release_counter": 0,
        "default_branch": "main",
        "archived": false,
        "created_at": "2026-06-24T11:33:56+12:00",
        "updated_at": "2026-09-10T00:42:47+12:00",
        "permissions": {
          "admin": false,
          "push": true,
          "pull": true
        },
        "has_issues": true,
        "internal_tracker": {
          "enable_time_tracker": true,
          "allow_only_contributors_to_track_time": true,
          "enable_issue_dependencies": true
        },
        "has_wiki": false,
        "has_pull_requests": true,
        "has_projects": false,
        "has_releases": true,
        "ignore_whitespace_conflicts": false,
        "allow_fast_forward_only_merge": true,
        "allow_merge_commits": true,
        "allow_rebase": true,
        "allow_rebase_explicit": true,
        "allow_squash_merge": true,
        "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
        "internal": false,
        "mirror_interval": "",
        "mirror_updated": "0001-01-01T00:00:00Z",
        "default_merge_style": "merge",
        "projects_mode": null,
        "default_delete_branch_after_merge": false,
        "object_format_name": "sha1"
      }
    },
    "merge_base": "7d02422b2617aace321e636d70746e9be2edde5c",
    "due_date": null,
    "created_at": "2026-09-09T23:52:40+12:00",
    "updated_at": "2026-09-10T00:42:47+12:00",
    "closed_at": "2026-09-10T00:42:45+12:00"
  },
  {
    "id": 42,
    "url": "https://forgejo.example.test/octocat/widgets/pulls/23",
    "number": 23,
    "user": {
      "id": 12,
      "login": "octocat",
      "login_name": "",
      "source_id": 0,
      "full_name": "",
      "email": "octocat@example.test",
      "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
      "language": "en-US",
      "is_admin": false,
      "last_login": "2026-05-25T18:27:26+12:00",
      "created": "2026-05-25T18:25:12+12:00",
      "restricted": false,
      "active": true,
      "prohibit_login": false,
      "location": "",
      "website": "",
      "description": "",
      "visibility": "private",
      "followers_count": 0,
      "following_count": 0,
      "starred_repos_count": 0
    },
    "title": "Sweep stale filename references",
    "body": "Sanitised capture.",
    "labels": [],
    "milestone": null,
    "assignee": null,
    "assignees": null,
    "state": "closed",
    "draft": false,
    "is_locked": false,
    "comments": 0,
    "html_url": "https://forgejo.example.test/octocat/widgets/pulls/23",
    "diff_url": "https://forgejo.example.test/octocat/widgets/pulls/23.diff",
    "patch_url": "https://forgejo.example.test/octocat/widgets/pulls/23.patch",
    "mergeable": false,
    "merged": false,
    "merged_at": null,
    "merge_commit_sha": null,
    "merged_by": null,
    "allow_maintainer_edit": false,
    "base": {
      "label": "main",
      "ref": "main",
      "sha": "9966f9e6845b1e1165ac04789daefde50b06e54a",
      "repo_id": 11,
      "repo": {
        "id": 11,
        "owner": {
          "id": 5,
          "login": "octocat",
          "login_name": "",
          "source_id": 0,
          "full_name": "",
          "email": "octocat@example.test",
          "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
          "language": "",
          "is_admin": false,
          "last_login": "0001-01-01T00:00:00Z",
          "created": "2026-05-12T10:55:46+12:00",
          "restricted": false,
          "active": false,
          "prohibit_login": false,
          "location": "",
          "website": "",
          "description": "",
          "visibility": "private",
          "followers_count": 0,
          "following_count": 0,
          "starred_repos_count": 0
        },
        "name": "widgets",
        "full_name": "octocat/widgets",
        "description": "Octocat widgets - primary repo",
        "empty": false,
        "private": true,
        "fork": false,
        "template": false,
        "parent": null,
        "mirror": false,
        "size": 9507,
        "html_url": "https://forgejo.example.test/octocat/widgets",
        "ssh_url": "ssh://git@forgejo.example.test/octocat/widgets.git",
        "clone_url": "https://forgejo.example.test/octocat/widgets.git",
        "original_url": "",
        "website": "",
        "stars_count": 0,
        "forks_count": 0,
        "watchers_count": 2,
        "open_issues_count": 0,
        "open_pr_counter": 2,
        "release_counter": 0,
        "default_branch": "main",
        "archived": false,
        "created_at": "2026-06-24T11:33:56+12:00",
        "updated_at": "2026-09-10T00:42:47+12:00",
        "permissions": {
          "admin": false,
          "push": true,
          "pull": true
        },
        "has_issues": true,
        "internal_tracker": {
          "enable_time_tracker": true,
          "allow_only_contributors_to_track_time": true,
          "enable_issue_dependencies": true
        },
        "has_wiki": false,
        "has_pull_requests": true,
        "has_projects": false,
        "has_releases": true,
        "ignore_whitespace_conflicts": false,
        "allow_fast_forward_only_merge": true,
        "allow_merge_commits": true,
        "allow_rebase": true,
        "allow_rebase_explicit": true,
        "allow_squash_merge": true,
        "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
        "internal": false,
        "mirror_interval": "",
        "mirror_updated": "0001-01-01T00:00:00Z",
        "default_merge_style": "merge",
        "projects_mode": null,
        "default_delete_branch_after_merge": false,
        "object_format_name": "sha1"
      }
    },
    "head": {
      "label": "chore/schema-and-comment-cleanup",
      "ref": "refs/pull/23/head",
      "sha": "381f0e92c6f71df69275c24847ce210e2da206d9",
      "repo_id": 11,
      "repo": {
        "id": 11,
        "owner": {
          "id": 5,
          "login": "octocat",
          "login_name": "",
          "source_id": 0,
          "full_name": "",
          "email": "octocat@example.test",
          "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
          "language": "",
          "is_admin": false,
          "last_login": "0001-01-01T00:00:00Z",
          "created": "2026-05-12T10:55:46+12:00",
          "restricted": false,
          "active": false,
          "prohibit_login": false,
          "location": "",
          "website": "",
          "description": "",
          "visibility": "private",
          "followers_count": 0,
          "following_count": 0,
          "starred_repos_count": 0
        },
        "name": "widgets",
        "full_name": "octocat/widgets",
        "description": "Octocat widgets - primary repo",
        "empty": false,
        "private": true,
        "fork": false,
        "template": false,
        "parent": null,
        "mirror": false,
        "size": 9507,
        "html_url": "https://forgejo.example.test/octocat/widgets",
        "ssh_url": "ssh://git@forgejo.example.test/octocat/widgets.git",
        "clone_url": "https://forgejo.example.test/octocat/widgets.git",
        "original_url": "",
        "website": "",
        "stars_count": 0,
        "forks_count": 0,
        "watchers_count": 2,
        "open_issues_count": 0,
        "open_pr_counter": 2,
        "release_counter": 0,
        "default_branch": "main",
        "archived": false,
        "created_at": "2026-06-24T11:33:56+12:00",
        "updated_at": "2026-09-10T00:42:47+12:00",
        "permissions": {
          "admin": false,
          "push": true,
          "pull": true
        },
        "has_issues": true,
        "internal_tracker": {
          "enable_time_tracker": true,
          "allow_only_contributors_to_track_time": true,
          "enable_issue_dependencies": true
        },
        "has_wiki": false,
        "has_pull_requests": true,
        "has_projects": false,
        "has_releases": true,
        "ignore_whitespace_conflicts": false,
        "allow_fast_forward_only_merge": true,
        "allow_merge_commits": true,
        "allow_rebase": true,
        "allow_rebase_explicit": true,
        "allow_squash_merge": true,
        "avatar_url": "https://forgejo.example.test/avatars/0000000000000000000000000000000000",
        "internal": false,
        "mirror_interval": "",
        "mirror_updated": "0001-01-01T00:00:00Z",
        "default_merge_style": "merge",
        "projects_mode": null,
        "default_delete_branch_after_merge": false,
        "object_format_name": "sha1"
      }
    },
    "merge_base": "637bbd6ca463a1c431bfc8bb65bc9c3e3d85d73a",
    "due_date": null,
    "created_at": "2026-07-21T23:23:40+12:00",
    "updated_at": "2026-07-21T23:27:53+12:00",
    "closed_at": "2026-07-21T23:27:53+12:00"
  }
]`;

/** `fgj pr view <n> --json` emits one object of the same shape — here, the merged one. */
// @effect-diagnostics-next-line preferSchemaOverJson:off
const listEntries = JSON.parse(FORGEJO_PR_LIST_JSON) as ReadonlyArray<unknown>;
// @effect-diagnostics-next-line preferSchemaOverJson:off
export const FORGEJO_PR_VIEW_JSON = JSON.stringify(listEntries[1]);

/** `fgj repo view <owner>/<name>`: labelled lines, no `--json`. */
export const FORGEJO_REPO_VIEW_OUTPUT = `Repository: octocat/widgets
Description: Octocat widgets - primary repo
URL: https://forgejo.example.test/octocat/widgets
Clone URL (HTTPS): https://forgejo.example.test/octocat/widgets.git
Clone URL (SSH): ssh://git@forgejo.example.test/octocat/widgets.git
Default Branch: main
Stars: 0
Forks: 0
Open Issues: 0
Private: true
Created: 2026-06-24 11:33:56
Updated: 2026-09-10 00:42:47
`;

/** `fgj auth status`, signed in to one instance. Exits 0. */
export const FORGEJO_AUTH_STATUS_AUTHENTICATED = `Authenticated instances:
  • forgejo.example.test (user: octocat)
`;

/** `fgj auth status` with no configured instance. Also exits 0 — only the body differs. */
export const FORGEJO_AUTH_STATUS_UNAUTHENTICATED = `Not authenticated with any Forgejo instances
Run 'fgj auth login' to authenticate
`;
